### ISSUE TITLE
Make licensing clear

### ISSUE THREAD

**Issue by kszucs** [ursa-labs/ursabot#105]
Pasting @wesm concerns about the license:

> What is the license of the ursabot codebase? Seems like it could be
GPL if Buildbot itself is [2] and you have reused any Buildbot code.
This is not mentioned in the README so I think you need to call this
out and advise people to be careful that any code contributed to this
codebase is stuck in GPL-land. Is it possible to separate the work
you've done from any GPL-ness? I don't think you can be too paranoid
about this kind of thing, and the longer you wait to draw a clear line
around any contaminated code the harder it will be to disentangle.

**Comment by wesm** [comment]
If possible I would recommend quarantining any lines you didn't write so we can try to make this code (minus GPL "dependencies" Apache-2)

**Comment by kszucs** [comment]
How should I quarantine those lines? I could use an example for it :)

**Comment by wesm** [comment]
Can you first identify the lines? Then we can decide what to do
