### ISSUE TITLE
Add C glib builders

### ISSUE THREAD

**Issue by kszucs** [ursa-labs/ursabot#154]
Steps (these could be documented in `projects/arrow/README.md`):

1. Add a new docker image with the required dependencies added, based on the [cpp one](https://github.com/ursa-labs/ursabot/blob/master/projects/arrow/arrow/docker.py#L41). 
2. Build the image(s) via `ursabot docker -n c_glib build` (assuming that the image is named as `c_glib`).
3. Add a builder based on the [CppTest builder](https://github.com/ursa-labs/ursabot/blob/master/projects/arrow/arrow/builders.py#L302) with c_glib specific steps and properties.
4. Add it to arrow's [master.cfg](https://github.com/ursa-labs/ursabot/blob/master/projects/arrow/master.cfg#L73-L104)
5. [Configure a scheduler](https://github.com/ursa-labs/ursabot/blob/master/projects/arrow/master.cfg#L161-L165) with the appropiate file change paths (`cpp/*` and `c_glib/*`)
6. Add an entry for the builder in the [.travis.yml](https://github.com/ursa-labs/ursabot/blob/master/.travis.yml#L121-L125) to test it automatically.

@kou would you like to pick up this issue?

**Comment by kou** [comment]
OK.
I'll work on this.

**Comment by kszucs** [comment]
Let me know if you've stucked with anything!

**Comment by kou** [comment]
I've created #172.
I used `c-glib` than `c_glib` for image name because we already use `-` in `cpp-benchmark`.
