### ISSUE TITLE
Limit Ninja threads in cpp and python builds

### ISSUE THREAD

**Issue by kszucs** [ursa-labs/ursabot#4]
Ninja utilizes all of the threads available on the worker. Running multiple builds in parallel generates too much load on the machines.

**Comment by fsaintjacques** [comment]
I'd fix this at the docker level.

**Comment by kszucs** [comment]
Via an environment variable?

**Comment by fsaintjacques** [comment]
https://docs.docker.com/config/containers/resource_constraints/#cpu

**Comment by kszucs** [comment]
Exaclty, that's my plan too.
> Somewhy I thought that You mean from **within** the container.

**Comment by kszucs** [comment]
resolved via https://github.com/ursa-labs/ursabot/pull/45
