### ISSUE TITLE
ARM64 builds are slow, make the worker max_builds=1

### ISSUE THREAD

**Issue by fsaintjacques** [ursa-labs/ursabot#59]

**Comment by kszucs** [comment]
On the long term We should aim for pretty flat rows in the [waterfall view](http://nashville.ursalabs.org:4100/#/waterfall). This slowness of arm builds bothers me. Not sure what's the best decision, but We probably cannot have multiple builder for our single jetson (at least right now).

**Comment by kszucs** [comment]
resolved by #87
